### ISSUE TITLE
unable to use it properly!

### ISSUE THREAD

**Issue by raziAkbar** [ineat/flutter-aws-appsync-sample#1]
it says no method getMessages on channel com.ineat.appsync! Can you help me out please

**Comment by mslimani** [comment]
No getMessages method exists in the flutter plugin but it exists in the graphql schema and the lambda. did you follow all the steps of the readme? If the plugin does not find this method it is because the resolvers steps located in the readme are not respected. Since the console on AWS AppSync are you able to run this method?

**Comment by raziAkbar** [comment]
yea i followed them and its working properly thanks @mslimani  for help.
